### PR TITLE
Add nmapxmlparser tests

### PR DESCRIPTION
**Pull request by cctechwiz**
Test have been added and debug printing for nmap objects was fixed.

Need some input on testing `extractNseAndSsh`.

### CODE REVIEW

**Comment by cctechwiz** [comment]
@marshall-sg I mentioned this in the PR details but thought I should tag it here too.

The `testExtractNseAndSsh` needs to be finished. I spent a decent amount of time on it and it seems really complicated to test well. Just wanted to get your input about this.

**Comment by cctechwiz** [comment]
I was definitely taking too big of a bite out of the nse and ssh tests initially. This is ready for review.

**Comment by marshall-sg** [comment]
I just noticed this, but I think we should rename `NmapXmlParser` to `ParserNmapXml` to be consistent with the other parser naming structure.  I can make the change while I am reviewing it if that sounds fine to you?

**Comment by cctechwiz** [comment]
Sounds good to me.

**Review by marshall-sg — APPROVED** [review]
Looks good.

**Pull request merged**
